server:
  port: 8003

mybatis:
  config-location: classpath:mybatis/mybatis.cfg.xml #mybatis配置文件所在路径
  type-aliases-package: com.sunquan.springcloud.entrty #所有实体类所在的包名
  mapper-locations:
    - classpath:mybatis/mapper/**/*.xml #mapper文件


spring:
  application:
    name: microservicecloud-dept
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: org.gjt.mm.mysql.Driver
    url: jdbc:mysql://localhost:3306/cloud01?useSSL=false&useUnicode=true&characterEncoding=utf8
    username: root
    password: sunquan92
    dbcp2:
      min-idle: 5                                           # 数据库连接池的最小维持连接数
      initial-size: 5                                       # 初始化连接数
      max-total: 5                                          # 最大连接数
      max-wait-millis: 200

eureka:
  client:
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka,http://eureka7002.com:7002/eureka,http://eureka7003.com:7003/eureka
  instance:
    instance-id: microservicecloud-dept8003


info:
  app.name: spring 练习
  company.name: 点亮鱼
  build.artifactId: $project.artifactId$
  build.version: $project.version$