#
#
#server:
#  prot: 7001
#
#eureka:
#  instance:
#    hostname: localhost #eureka服务端的实例名称
#  client:
#    register-with-eureka: false #false表示不想注册中心注册自己
#    fetch-register: false #false表示我自己就是注册中心，我的职责是维护服务实例，不需要检索服务
#    service-url:
#      defualtZone: http://${eureka.instance.hostname}:${server.port}/eureka/
#      #设置与Eureka Server 交互的地址，检查服务和注册服务都需要依赖这个地址

server:
  port: 7001

eureka:
  instance:
    hostname: localhost #eureka服务端的实例名称
  client:
    register-with-eureka: false     #false表示不向注册中心注册自己。
    fetch-registry: false     #false表示自己端就是注册中心，我的职责就是维护服务实例，并不需要去检索服务
    service-url:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/       #设置与Eureka Server交互的地址查询服务和注册服务都需要依赖这个地址（单机）。



